name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: node --version
    - run: npm --version
    - uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-      
    - run: npm ci
    - run: npm run test:headless
    - run: npm run lint
    - name: Run headless test
      uses: GabrielBB/xvfb-action@v1.0
      with:
        run: npm run e2e
    - run: npm run build:release        
